# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
production:
  adapter: redis
  url: redis://localhost:6379/1
  # adapter: postgresql
  # url: postgres://localhost/just_chatting

development:
  # adapter: async
  adapter: postgresql
  url: postgres://localhost/just_chatting_development

test:
  adapter: async
  # adapter: postgresql
  # url: postgres://localhost/just_chatting_test
